package enums;

public enum ErrorEnum {
	READXMLERROR("READXMLERROR"),
	KEY_GENERATION_ERROR_NEFTIN("KEYERROR_NEFTIN"),
	SQL_ERROR_NEFTIN("SQLERROR_NEFTIN"),
	
	KEY_GENERATION_ERROR_NEFTINNODE("KEYERROR_NEFTINNODE"),
	SQL_ERROR_NEFTINNODE("SQLERROR_NEFTINNODE"),
	
	KEY_GENERATION_ERROR_NEFTINDET("KEYERROR_NEFTINDET"),
	SQL_ERROR_NEFTINDET("SQLERROR_NEFTINDET"),
	
	KEY_GENERATION_ERROR_NEFTINMSG("KEYERROR_NEFTINMSG"),
	SQL_ERROR_NEFTINMSG("SQLERROR_NEFTINMSG"),
	
	SQL_ERROR_NEFTMSGIN("SQLERROR_NEFTMSGIN"),
	
	GETFILE_ERROR("GETFILE"),
	DUPFILE_ERROR("DUPFILE"),
	BEANCREATION_ERROR("JAVABEAN_ERROR"),
	TEXTFILECREATION_ERROR("TXTFILE_ERROR"),
	
	ERRTABLEINSERT_ERROR("ERR_TBL_ERROR"),
	
	
	SQL_ERROR("SQLERROR"),
	SFTP_INSTANCE_ERROR("SFTPERROR_INSTANCE"),//added for sftp
	SFTP_ERROR("SFTPERROR"),
	RENAMEERROR("RENAMEeRR");
	private String statusCode;
 
	private ErrorEnum(String s) {
		statusCode = s;
	}
 
	public String getStatusCode() {
		return statusCode;
	}
}
