  CREATE TABLE NEFT_IN
   (	"TRAN_REF_NO" CHAR(16 BYTE), 
	"TRAN_REF_RETURN_UTR" CHAR(16 BYTE), 
	"BATCH_TIME" CHAR(6 BYTE), 
	"IFSC_SENDER" CHAR(15 BYTE) DEFAULT (LPAD(CHR(0),015,CHR(0))), 
	"SENDER_ACCT_TYPE" CHAR(3 BYTE) DEFAULT (LPAD(CHR(0),003,CHR(0))), 
	"SENDER_ACCT_NO" CHAR(35 BYTE) DEFAULT (LPAD(CHR(0),035,CHR(0))), 
	"SENDER_ACCT_NAME" CHAR(70 BYTE) DEFAULT (LPAD(CHR(0),070,CHR(0))), 
	"REMITTER_DETAIL" CHAR(150 BYTE) DEFAULT (LPAD(CHR(0),150,CHR(0))), 
	"IFSC_RECVR" CHAR(15 BYTE) DEFAULT (LPAD(CHR(0),015,CHR(0))), 
	"RECVR_ACCT_TYPE" CHAR(3 BYTE) DEFAULT (LPAD(CHR(0),003,CHR(0))), 
	"RECVR_ACCT_NO" CHAR(35 BYTE) DEFAULT (LPAD(CHR(0),035,CHR(0))), 
	"RECVR_ACCT_NAME" CHAR(70 BYTE) DEFAULT (LPAD(CHR(0),070,CHR(0))), 
	"BENEF_ADDRS" CHAR(182 BYTE) DEFAULT (LPAD(CHR(0),182,CHR(0))), 
	"REMIT_INFO" CHAR(250 BYTE) DEFAULT (LPAD(CHR(0),250,CHR(0))), 
	"REJECT_CODE" CHAR(4 BYTE) DEFAULT (LPAD(CHR(0),004,CHR(0))), 
	"REJECT_REASON" CHAR(100 BYTE) DEFAULT (LPAD(CHR(0),100,CHR(0))), 
	"AMOUNT" VARCHAR2(50 BYTE) DEFAULT (0), 
	"ORG_TRAN_DATE" CHAR(8 BYTE) DEFAULT (LPAD(CHR(0),008,CHR(0))), 
	"TRAN_DATE" CHAR(8 BYTE) DEFAULT (LPAD(CHR(0),008,CHR(0))), 
	"ACK_NACK" CHAR(1 BYTE) DEFAULT (0), 
	"ACK_NACK_FROM_CBS" CHAR(1 BYTE) DEFAULT (0), 
	"BANKNAME" CHAR(6 BYTE) DEFAULT (LPAD(CHR(0),006,CHR(0))),  
	"FLAG_FILE_CREATED" CHAR(1 BYTE) DEFAULT (0), 
	"ACK_NACK_MSG" CLOB, 
	"ACK_NACK_SEND_MQ" CHAR(1 BYTE) DEFAULT (0), 
	"TRAN_BRANCH" CHAR(5 BYTE) DEFAULT (LPAD(CHR(0),005,CHR(0))), 
	"REF_NO" VARCHAR2(20 BYTE), 
	"SEQINHEADER" CHAR(9 BYTE), 
	"MSG_TYPE" CHAR(3 BYTE) DEFAULT (0), 
	"CREATION_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LAST_MOD_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) ;
   
     ALTER TABLE NEFT_IN ADD CONSTRAINT "NEFTPK_IN" PRIMARY KEY ("TRAN_REF_NO");

     
     alter table neft_in rename column THERE_FILENAME to THEIR_FILENAME;
     
     ALTER TABLE neft_in
MODIFY REF_NO VARCHAR2(30);
ALTER TABLE neft_msg_in
MODIFY REF_NO VARCHAR2(30);

ALTER TABLE neft_in
MODIFY TRAN_REF_NO VARCHAR2(16);